routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;



Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    // Company Route
    Route::resource('company',CompanyController::class);

    // Company Route
    Route::resource('employe',EmployeeController::class);

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];


    // public function employee()
    // {
    //     return $this->hasMany(Employee::class);
    // }

}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use Illuminate\Http\Request;
use App\Http\Requests\CompanyRequest;


class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companys = Company::latest()->paginate(10);
        return view('company.index',compact('companys'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        // Validate
        $validator = $request->validated();

           $name = $request->file('logo')->getClientOriginalExtension();
           $image_path = $request->file('logo')->store('logo', 'public');
           Company::create([
                'name'=>$request->name,
                'email'=>$request->email,
                'logo'=>$request-> $name.$image_path,
                'website'=>$request->website,
            ]);

        return Redirect()->back()->with('success','Company Added Success');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('company.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, Company $company)
    {

        $company->update([
            'name'=>$request->name,
            'email'=>$request->email,
            'website'=>$request->website,
        ]);

        if ($request->has('logo') ) {
            unlink('storage/'.$company->logo);

            $name = $request->file('logo')->getClientOriginalExtension();
            $image_path = $request->file('logo')->store('logo', 'public');

            $company->update(['logo'=>$request->$name.$image_path]);

             return Redirect()->route('company.index')->with('success','image successfully Updated');
         }
        return Redirect()->route('company.index')->with('success','Company Data Update Success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)

    {
       $company->delete();
       return Redirect()->back()->with('success','Delete Data Success');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/company/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight d-flex justify-content-evenly">
            <a href="{{ url('company') }}"><button class="btn btn-outline-dark ">Companyes</button></a>
            ||--||
            <a href="{{ url('employe') }}"><button class="btn btn-outline-dark">Employee</button></a>
        </h2>
    </x-slot>

    <div class="container mt-4 ">
        <div class="text-center">
            <b>Update Company Information</b>
        </div>
    </div>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <form action="{{ route('company.update', $company->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="mb-1">
                        <label for="name" class="col-form-label">Company Name:</label>
                        <input type="text" name="name" class="form-control" value="{{ $company->name }}">
                    </div>
                    <div class="mb-1">
                        <label for="email" class="col-form-label">E-Mail:</label>
                        <input type="text" name="email" class="form-control" value="{{ $company->email }}">
                    </div>
                    <div class="mb-1">
                        <img src="{{ asset('storage/'.$company->logo) }}" width="100px;" height="100px;" alt="OldLogo">
                        <label for="logo" class="col-form-label">Logo:</label>
                        <input type="file" name="logo" class="form-control">
                    </div>
                    <div class="mb-1">
                        <label for="website" class="col-form-label">Website:</label>
                        <input type="text" name="website" class="form-control" value="{{ $company->website }}">
                    </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary text-dark">Update Data</button>
            </div>
            </form>
        </div>
    </div>
    </div>
    </div>


    <!-- Button trigger modal -->

    </div>

</x-app-layout>

resources/views/company/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight d-flex justify-content-evenly">
            <a href="{{ url('company') }}"><button class="btn btn-outline-dark ">Companyes</button></a>
            ||--||
            <a href="{{ url('employe') }}"><button class="btn btn-outline-dark">Employee</button></a>
        </h2>
    </x-slot>

    <div class="container mt-5 ">
        <div class="float-end">
            <h2 class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Add Company
            </h2>
        </div>
    </div>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Logo</th>
                            <th scope="col">Website</th>
                            <th class="float-end" scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($companys as $company)
                            <tr>
                                <th scope="row">{{ $companys->firstItem() + $loop->index }}</th>
                                <td>{{ $company->name }}</td>
                                <td>{{ $company->email }}</td>
                                <td><img src="{{ asset('storage/'.$company->logo) }}" width="50px;" height="50px;" alt="">
                                </td>
                                <td>{{ $company->website }}</td>
                                <td class="float-end">
                                    <a href="{{ route('company.edit', $company->id) }}"
                                        class="btn btn-primary a-btn-slide-text">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                        <span><strong>Edit</strong></span>
                                    </a>
                                    <form class="btn btn-primary a-btn-slide-text"
                                        action="{{ route('company.destroy', $company->id) }}" method="post">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit"><span><strong>Delete</strong></span></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $companys->withQueryString()->links() !!}
            </div>
        </div>
    </div>
    </div>


    <!-- Button trigger modal -->


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Company Details</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('company.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" name="name" class="form-control" id="name">
                        </div>
                        <div class="mb-3">
                            <label for="email" class="col-form-label">Email:</label>
                            <input type="text" name="email" class="form-control" id="email">
                        </div>
                        <div class="mb-3">
                            <label for="logo" class="col-form-label">logo:</label>
                            <input type="file" name="logo" class="form-control" id="logo">
                        </div>
                        <div class="mb-3">
                            <label for="website" class="col-form-label">Website:</label>
                            <input type="text" name="website" class="form-control" id="website">
                        </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary text-dark" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary text-dark">Save Data</button>
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>

</x-app-layout>